/**
 * Generates `supabase/seed.sql` from the demo catalog.
 *
 *   npm run seed:sql
 *
 * Paste the output into the Supabase SQL editor after running schema.sql.
 * The statements are idempotent (ON CONFLICT DO UPDATE keyed on slug), so
 * re-running never creates duplicates.
 */

import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { buildCatalog, defaultSettings } from '../data/build-catalog.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

/** Postgres literal for a JS value. */
function lit(value) {
  if (value === null || value === undefined) return 'NULL';
  if (typeof value === 'number') return Number.isFinite(value) ? String(value) : 'NULL';
  if (typeof value === 'boolean') return value ? 'true' : 'false';
  if (Array.isArray(value)) {
    return value.length ? `ARRAY[${value.map(lit).join(',')}]::text[]` : `'{}'::text[]`;
  }
  return `'${String(value).replace(/'/g, "''")}'`;
}

function insert(table, rows, columns, conflictKey, updateColumns) {
  if (!rows.length) return '';
  const head = `insert into public.${table} (${columns.join(', ')}) values`;
  const body = rows
    .map((row) => `  (${columns.map((c) => lit(row[c])).join(', ')})`)
    .join(',\n');
  const update = updateColumns
    .map((c) => `${c} = excluded.${c}`)
    .join(', ');
  return `${head}\n${body}\non conflict (${conflictKey}) do update set ${update};\n`;
}

async function main() {
  const { categories, brands, products } = buildCatalog();

  // Parents must exist before children, because parent_id is a foreign key.
  const parents = categories.filter((c) => !c.parent_id);
  const children = categories.filter((c) => c.parent_id);

  const categoryColumns = [
    'id', 'slug', 'name', 'name_si', 'name_ta', 'image_url', 'icon',
    'parent_id', 'is_active', 'sort_order',
  ];
  const brandColumns = ['id', 'slug', 'name', 'is_active'];
  const productColumns = [
    'id', 'slug', 'sku', 'name', 'name_si', 'name_ta', 'description',
    'category_id', 'subcategory_id', 'brand_id', 'price', 'sale_price',
    'stock', 'low_stock_threshold', 'unit', 'weight', 'image_url', 'gallery',
    'is_featured', 'is_new', 'is_best_seller', 'is_active', 'popularity',
  ];

  const parts = [
    '-- ==========================================================================',
    '--  Lucky Traders — demo catalog seed',
    `--  ${categories.length} categories · ${brands.length} brands · ${products.length} products`,
    '--  Generated by `npm run seed:sql`. Run supabase/schema.sql first.',
    '--  Safe to re-run: every statement upserts on its unique slug.',
    '-- ==========================================================================',
    '',
    'begin;',
    '',
    '-- --------------------------------------------------------- categories',
    insert('categories', parents, categoryColumns, 'slug', ['name', 'name_si', 'name_ta', 'icon', 'is_active', 'sort_order']),
    insert('categories', children, categoryColumns, 'slug', ['name', 'name_si', 'name_ta', 'parent_id', 'is_active', 'sort_order']),
    '-- ------------------------------------------------------------- brands',
    insert('brands', brands, brandColumns, 'slug', ['name', 'is_active']),
    '-- ----------------------------------------------------------- products',
  ];

  // Chunked so no single statement grows unreasonably large for the editor.
  const CHUNK = 50;
  for (let i = 0; i < products.length; i += CHUNK) {
    parts.push(
      insert('products', products.slice(i, i + CHUNK), productColumns, 'slug', [
        'sku', 'name', 'name_si', 'name_ta', 'description', 'category_id',
        'subcategory_id', 'brand_id', 'price', 'sale_price', 'stock', 'unit',
        'weight', 'is_featured', 'is_new', 'is_best_seller', 'is_active', 'popularity',
      ]),
    );
  }

  parts.push(
    '-- ----------------------------------------------------------- settings',
    `insert into public.settings (id, data) values (1, ${lit(JSON.stringify(defaultSettings))}::jsonb)`,
    'on conflict (id) do update set data = excluded.data, updated_at = now();',
    '',
    'commit;',
    '',
  );

  const outPath = path.join(root, 'supabase', 'seed.sql');
  await fs.mkdir(path.dirname(outPath), { recursive: true });
  await fs.writeFile(outPath, parts.join('\n'), 'utf8');

  const bytes = (await fs.stat(outPath)).size;
  console.log(`Wrote supabase/seed.sql`);
  console.log(`  ${categories.length} categories, ${brands.length} brands, ${products.length} products`);
  console.log(`  ${(bytes / 1024).toFixed(0)} KB`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
